import { LLDProblem, Project, Snippet } from './models.js';

const commonErr = `export function errorHandler(err, req, res, next) {
  const status = err.statusCode || 500;
  res.status(status).json({ success: false, data: null, error: err.message || 'Internal server error' });
}`;

const projects = [
{
 name:'URL Shortener API',description:'Beginner Express/Mongoose service with redirects, click analytics and centralized errors.',category:'express',difficulty:'beginner',estimatedMinutes:45,
 folderTree:['src/','src/config/','src/config/db.js','src/models/','src/models/url.model.js','src/controllers/','src/controllers/url.controller.js','src/routes/','src/routes/url.routes.js','src/middleware/','src/middleware/errorHandler.js','src/utils/','src/utils/generateShortCode.js','src/app.js','src/server.js','tests/','tests/url.test.js','.env.example','README.md'],
 files:[
 {path:'src/config/db.js',layer:'config',order:1,code:`import mongoose from 'mongoose';\nexport const connectDB = () => mongoose.connect(process.env.MONGO_URI);`},
 {path:'src/models/url.model.js',layer:'model',order:2,code:`import mongoose from 'mongoose';\nconst schema = new mongoose.Schema({ originalUrl:{type:String,required:true}, shortCode:{type:String,required:true,unique:true,index:true}, clicks:{type:Number,default:0}, createdAt:{type:Date,default:Date.now} });\nexport const Url = mongoose.model('Url', schema);`},
 {path:'src/utils/generateShortCode.js',layer:'util',order:3,code:`import { nanoid } from 'nanoid';\nexport const generateShortCode = () => nanoid(7);`},
 {path:'src/controllers/url.controller.js',layer:'controller',order:4,code:`import { Url } from '../models/url.model.js';\nimport { generateShortCode } from '../utils/generateShortCode.js';\nexport async function shorten(req,res,next){try{const doc=await Url.create({originalUrl:req.body.originalUrl,shortCode:generateShortCode()});res.status(201).json({success:true,data:doc,error:null});}catch(e){next(e);}}\nexport async function redirect(req,res,next){try{const doc=await Url.findOneAndUpdate({shortCode:req.params.code},{\\$inc:{clicks:1}},{new:true});if(!doc)return res.status(404).json({success:false,data:null,error:'Not found'});res.redirect(doc.originalUrl);}catch(e){next(e);}}\nexport async function stats(req,res,next){try{const doc=await Url.findOne({shortCode:req.params.code});if(!doc)return res.status(404).json({success:false,data:null,error:'Not found'});res.json({success:true,data:{shortCode:doc.shortCode,clicks:doc.clicks,createdAt:doc.createdAt},error:null});}catch(e){next(e);}}`},
 {path:'src/routes/url.routes.js',layer:'route',order:5,code:`import { Router } from 'express';\nimport { shorten,stats } from '../controllers/url.controller.js';\nconst router=Router();\nrouter.post('/shorten',shorten);\nrouter.get('/stats/:code',stats);\nexport default router;`},
 {path:'src/middleware/errorHandler.js',layer:'middleware',order:6,code:commonErr},
 {path:'src/app.js',layer:'config',order:7,code:`import express from 'express';\nimport routes from './routes/url.routes.js';\nimport { redirect } from './controllers/url.controller.js';\nimport { errorHandler } from './middleware/errorHandler.js';\nconst app=express();app.use(express.json());app.use('/api',routes);app.get('/:code',redirect);app.use(errorHandler);export default app;`},
 {path:'src/server.js',layer:'config',order:8,code:`import 'dotenv/config';import app from './app.js';import { connectDB } from './config/db.js';\nawait connectDB();app.listen(process.env.PORT||3000,()=>console.log('server started'));`},
 {path:'tests/url.test.js',layer:'test',order:9,code:`import request from 'supertest';import app from '../src/app.js';\ndescribe('URL API',()=>{it('rejects missing originalUrl',async()=>{const r=await request(app).post('/api/shorten').send({});expect(r.status).toBeGreaterThanOrEqual(400);});});`},
 {path:'.env.example',layer:'config',order:10,code:'MONGO_URI=mongodb://localhost:27017/shortener\nPORT=3000'},
 {path:'README.md',layer:'readme',order:11,code:'# URL Shortener API\n\nPOST /api/shorten, GET /:code, GET /api/stats/:code.'}
 ]},
{
 name:'Rate Limiter Service',description:'Intermediate Express middleware backed by a reusable token-bucket service.',category:'express',difficulty:'intermediate',estimatedMinutes:60,
 folderTree:['src/','src/config/index.js','src/services/tokenBucket.service.js','src/middleware/rateLimiter.middleware.js','src/routes/api.routes.js','src/utils/redisClient.js','src/app.js','src/server.js','tests/rateLimiter.test.js','README.md'],
 files:[
 {path:'src/config/index.js',layer:'config',order:1,code:`export const config={port:Number(process.env.PORT||3000),defaultCapacity:Number(process.env.RATE_LIMIT_CAPACITY||10),defaultRefill:Number(process.env.RATE_LIMIT_REFILL||1)};`},
 {path:'src/services/tokenBucket.service.js',layer:'service',order:2,code:`export class TokenBucket{constructor(capacity,refillPerSecond){this.capacity=capacity;this.tokens=capacity;this.refillPerSecond=refillPerSecond;this.lastRefill=Date.now();}consume(cost=1){const now=Date.now();this.tokens=Math.min(this.capacity,this.tokens+(now-this.lastRefill)/1000*this.refillPerSecond);this.lastRefill=now;if(this.tokens<cost)return {allowed:false,retryAfter:Math.ceil((cost-this.tokens)/this.refillPerSecond)};this.tokens-=cost;return {allowed:true,retryAfter:0};}}`},
 {path:'src/middleware/rateLimiter.middleware.js',layer:'middleware',order:3,code:`import { TokenBucket } from '../services/tokenBucket.service.js';\nconst buckets=new Map();export const rateLimit=({capacity,refillPerSecond})=>(req,res,next)=>{const key=req.ip+req.route?.path;let bucket=buckets.get(key);if(!bucket){bucket=new TokenBucket(capacity,refillPerSecond);buckets.set(key,bucket);}const r=bucket.consume();if(!r.allowed){res.set('Retry-After',String(r.retryAfter));return res.status(429).json({success:false,data:null,error:'Rate limit exceeded'});}next();};`},
 {path:'src/routes/api.routes.js',layer:'route',order:4,code:`import { Router } from 'express';import { rateLimit } from '../middleware/rateLimiter.middleware.js';const router=Router();router.get('/public',rateLimit({capacity:5,refillPerSecond:1}),(req,res)=>res.json({success:true,data:'ok',error:null}));export default router;`},
 {path:'src/utils/redisClient.js',layer:'util',order:5,code:`// Replace this in-memory Map adapter with Redis when horizontal scaling is required.\nexport const bucketStore=new Map();`},
 {path:'src/app.js',layer:'config',order:6,code:`import express from 'express';import routes from './routes/api.routes.js';const app=express();app.use('/api',routes);export default app;`},
 {path:'src/server.js',layer:'config',order:7,code:`import 'dotenv/config';import app from './app.js';import { config } from './config/index.js';app.listen(config.port,()=>console.log('rate limiter listening'));`},
 {path:'tests/rateLimiter.test.js',layer:'test',order:8,code:`import { TokenBucket } from '../src/services/tokenBucket.service.js';test('blocks once empty',()=>{const b=new TokenBucket(1,0.001);expect(b.consume().allowed).toBe(true);expect(b.consume().allowed).toBe(false);});`},
 {path:'README.md',layer:'readme',order:9,code:'# Rate Limiter Service\n\nToken bucket middleware factory with Retry-After on HTTP 429.'}
 ]},
{
 name:'E-commerce Cart & Order Service with Queue',description:'Advanced layered Express service with JWT auth, validation, simulated queue processing and inventory circuit breaker.',category:'express',difficulty:'advanced',estimatedMinutes:90,
 folderTree:['src/','src/config/db.js','src/config/queue.js','src/models/cart.model.js','src/models/order.model.js','src/models/product.model.js','src/controllers/cart.controller.js','src/controllers/order.controller.js','src/services/cart.service.js','src/services/order.service.js','src/services/inventory.client.js','src/queues/orderProcessor.queue.js','src/middleware/auth.middleware.js','src/middleware/errorHandler.js','src/middleware/validate.middleware.js','src/validators/order.validator.js','src/routes/cart.routes.js','src/routes/order.routes.js','src/app.js','src/server.js','tests/order.test.js','README.md'],
 files:[
 {path:'src/config/db.js',layer:'config',order:1,code:`import mongoose from 'mongoose';export const connectDB=()=>mongoose.connect(process.env.MONGO_URI);`},
 {path:'src/config/queue.js',layer:'config',order:2,code:`import { EventEmitter } from 'node:events';export const orderQueue=new EventEmitter();export const publishOrder=(order)=>setImmediate(()=>orderQueue.emit('order.created',order));`},
 {path:'src/models/cart.model.js',layer:'model',order:3,code:`import mongoose from 'mongoose';const s=new mongoose.Schema({userId:{type:String,index:true},items:[{productId:String,quantity:Number,price:Number}]},{timestamps:true});export const Cart=mongoose.model('Cart',s);`},
 {path:'src/models/order.model.js',layer:'model',order:4,code:`import mongoose from 'mongoose';const s=new mongoose.Schema({userId:String,items:Array,total:Number,status:{type:String,default:'PENDING'}},{timestamps:true});export const Order=mongoose.model('Order',s);`},
 {path:'src/models/product.model.js',layer:'model',order:5,code:`import mongoose from 'mongoose';const s=new mongoose.Schema({name:String,price:Number,stock:Number});export const Product=mongoose.model('Product',s);`},
 {path:'src/services/inventory.client.js',layer:'service',order:6,code:`let failures=0,openUntil=0;export async function reserveInventory(items){if(Date.now()<openUntil)throw new Error('Inventory circuit open');try{if(!items.length)throw new Error('No items');failures=0;return {reserved:true};}catch(e){failures++;if(failures>=3)openUntil=Date.now()+5000;throw e;}}`},
 {path:'src/services/cart.service.js',layer:'service',order:7,code:`import { Cart } from '../models/cart.model.js';export const getCart=(userId)=>Cart.findOne({userId});export async function addItem(userId,item){return Cart.findOneAndUpdate({userId},{\\$push:{items:item}},{upsert:true,new:true});}`},
 {path:'src/services/order.service.js',layer:'service',order:8,code:`import { Order } from '../models/order.model.js';import { reserveInventory } from './inventory.client.js';import { publishOrder } from '../config/queue.js';export async function createOrder(userId,items){await reserveInventory(items);const total=items.reduce((s,i)=>s+i.price*i.quantity,0);const order=await Order.create({userId,items,total});publishOrder(order);return order;}`},
 {path:'src/controllers/cart.controller.js',layer:'controller',order:9,code:`import * as carts from '../services/cart.service.js';export async function get(req,res,next){try{res.json({success:true,data:await carts.getCart(req.user.id),error:null});}catch(e){next(e);}}export async function add(req,res,next){try{res.status(201).json({success:true,data:await carts.addItem(req.user.id,req.body),error:null});}catch(e){next(e);}}`},
 {path:'src/controllers/order.controller.js',layer:'controller',order:10,code:`import { createOrder } from '../services/order.service.js';export async function create(req,res,next){try{const data=await createOrder(req.user.id,req.body.items);res.status(202).json({success:true,data,error:null});}catch(e){next(e);}}`},
 {path:'src/queues/orderProcessor.queue.js',layer:'service',order:11,code:`import { orderQueue } from '../config/queue.js';import { Order } from '../models/order.model.js';export function startOrderProcessor(){orderQueue.on('order.created',async(order)=>{await Order.findByIdAndUpdate(order._id,{status:'PROCESSING'});});}`},
 {path:'src/middleware/auth.middleware.js',layer:'middleware',order:12,code:`import jwt from 'jsonwebtoken';export function auth(req,res,next){try{const token=req.headers.authorization?.replace('Bearer ','');if(!token)return res.status(401).json({success:false,data:null,error:'Unauthorized'});req.user=jwt.verify(token,process.env.JWT_SECRET);next();}catch(e){res.status(401).json({success:false,data:null,error:'Invalid token'});}}`},
 {path:'src/middleware/errorHandler.js',layer:'middleware',order:13,code:commonErr},
 {path:'src/middleware/validate.middleware.js',layer:'middleware',order:14,code:`export const validate=(schema)=>(req,res,next)=>{const parsed=schema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,data:null,error:parsed.error.flatten()});req.body=parsed.data;next();};`},
 {path:'src/validators/order.validator.js',layer:'middleware',order:15,code:`import { z } from 'zod';export const orderSchema=z.object({items:z.array(z.object({productId:z.string(),quantity:z.number().int().positive(),price:z.number().nonnegative()})).min(1)});`},
 {path:'src/routes/cart.routes.js',layer:'route',order:16,code:`import { Router } from 'express';import { auth } from '../middleware/auth.middleware.js';import * as c from '../controllers/cart.controller.js';const r=Router();r.use(auth);r.get('/',c.get);r.post('/items',c.add);export default r;`},
 {path:'src/routes/order.routes.js',layer:'route',order:17,code:`import { Router } from 'express';import { auth } from '../middleware/auth.middleware.js';import { validate } from '../middleware/validate.middleware.js';import { orderSchema } from '../validators/order.validator.js';import { create } from '../controllers/order.controller.js';const r=Router();r.post('/',auth,validate(orderSchema),create);export default r;`},
 {path:'src/app.js',layer:'config',order:18,code:`import express from 'express';import carts from './routes/cart.routes.js';import orders from './routes/order.routes.js';import { errorHandler } from './middleware/errorHandler.js';const app=express();app.use(express.json());app.use('/api/cart',carts);app.use('/api/orders',orders);app.use(errorHandler);export default app;`},
 {path:'src/server.js',layer:'config',order:19,code:`import 'dotenv/config';import app from './app.js';import { connectDB } from './config/db.js';import { startOrderProcessor } from './queues/orderProcessor.queue.js';await connectDB();startOrderProcessor();app.listen(process.env.PORT||3000);`},
 {path:'tests/order.test.js',layer:'test',order:20,code:`import { createOrder } from '../src/services/order.service.js';describe('order service',()=>{it('requires items',async()=>{await expect(createOrder('u1',[])).rejects.toThrow();});});`},
 {path:'README.md',layer:'readme',order:21,code:'# Cart & Order Service\n\nLayered cart/order API with JWT, validation, async queue processing and inventory protection.'}
 ]}
];

const lld=[
{name:'Parking Lot System',difficulty:'advanced',language:'cpp',problemStatement:'Design a parking lot with multiple floors, spot types, vehicle types, tickets, payment and swappable spot assignment.',classDiagram:[
{className:'Vehicle',type:'class',fields:['license','type'],methods:['type()']},{className:'ParkingSpot',type:'class',fields:['id','occupied'],methods:['canFit()','park()','leave()']},{className:'SpotAssignmentStrategy',type:'interface',fields:[],methods:['findSpot()']},{className:'ParkingLot',type:'class',fields:['floors','strategy'],methods:['park()','exit()']}
],files:[{path:'parking_lot.cpp',pattern:'Strategy / Factory',code:`#include <bits/stdc++.h>\nusing namespace std;\nenum class VehicleType{Motorcycle,Car,Truck}; enum class SpotType{Compact,Large,Handicapped};\nclass Vehicle{public:string license;VehicleType kind;Vehicle(string l,VehicleType k):license(move(l)),kind(k){}virtual ~Vehicle()=default;};\nclass Car:public Vehicle{public:Car(string l):Vehicle(move(l),VehicleType::Car){}};class Motorcycle:public Vehicle{public:Motorcycle(string l):Vehicle(move(l),VehicleType::Motorcycle){}};class Truck:public Vehicle{public:Truck(string l):Vehicle(move(l),VehicleType::Truck){}};\nclass ParkingSpot{protected:string id;bool occupied=false;SpotType kind;public:ParkingSpot(string i,SpotType k):id(move(i)),kind(k){}virtual bool canFit(const Vehicle&)=0;bool park(const Vehicle& v){if(occupied||!canFit(v))return false;occupied=true;return true;}void leave(){occupied=false;}bool free()const{return !occupied;}virtual~ParkingSpot()=default;};\nclass CompactSpot:public ParkingSpot{public:CompactSpot(string i):ParkingSpot(move(i),SpotType::Compact){}bool canFit(const Vehicle&v)override{return v.kind!=VehicleType::Truck;}};class LargeSpot:public ParkingSpot{public:LargeSpot(string i):ParkingSpot(move(i),SpotType::Large){}bool canFit(const Vehicle&)override{return true;}};class HandicappedSpot:public ParkingSpot{public:HandicappedSpot(string i):ParkingSpot(move(i),SpotType::Handicapped){}bool canFit(const Vehicle&)override{return true;}};\nclass SpotAssignmentStrategy{public:virtual ParkingSpot* findSpot(vector<unique_ptr<ParkingSpot>>&spots,const Vehicle&v)=0;virtual~SpotAssignmentStrategy()=default;};class FirstFitStrategy:public SpotAssignmentStrategy{public:ParkingSpot* findSpot(vector<unique_ptr<ParkingSpot>>&s,const Vehicle&v)override{for(auto&p:s)if(p->free()&&p->canFit(v))return p.get();return nullptr;}};\nstruct Ticket{string id,license;chrono::steady_clock::time_point entry;};class PaymentProcessor{public:virtual bool pay(double)=0;virtual~PaymentProcessor()=default;};class CashPayment:public PaymentProcessor{public:bool pay(double)override{return true;}};\nclass ParkingFloor{public:vector<unique_ptr<ParkingSpot>>spots;};class ParkingLot{vector<ParkingFloor>floors;unique_ptr<SpotAssignmentStrategy>strategy;public:ParkingLot():strategy(make_unique<FirstFitStrategy>()){}optional<Ticket> park(const Vehicle&v){for(auto&f:floors)if(auto*s=strategy->findSpot(f.spots,v);s&&s->park(v))return Ticket{to_string(rand()),v.license,chrono::steady_clock::now()};return nullopt;}};\n`}]},
{name:'LRU Cache',difficulty:'intermediate',language:'cpp',problemStatement:'Implement O(1) get and put using a hashmap plus doubly linked list.',classDiagram:[{className:'Node',type:'class',fields:['key','value','prev','next'],methods:[]},{className:'LRUCache',type:'class',fields:['capacity','map','head','tail'],methods:['get()','put()']}],files:[{path:'lru_cache.cpp',pattern:'none',code:`#include <bits/stdc++.h>\nusing namespace std;\nclass LRUCache{struct Node{int k,v;Node*prev,*next;Node(int K,int V):k(K),v(V),prev(nullptr),next(nullptr){}};int cap;unordered_map<int,Node*>mp;Node head{0,0},tail{0,0};void remove(Node*n){n->prev->next=n->next;n->next->prev=n->prev;}void addFront(Node*n){n->next=head.next;n->prev=&head;head.next->prev=n;head.next=n;}public:LRUCache(int c):cap(c){head.next=&tail;tail.prev=&head;}int get(int k){if(!mp.count(k))return -1;Node*n=mp[k];remove(n);addFront(n);return n->v;}void put(int k,int v){if(mp.count(k)){Node*n=mp[k];n->v=v;remove(n);addFront(n);return;}if((int)mp.size()==cap){Node*n=tail.prev;remove(n);mp.erase(n->k);delete n;}Node*n=new Node(k,v);mp[k]=n;addFront(n);}};\n`}]},
{name:'Rate Limiter Strategies',difficulty:'intermediate',language:'cpp',problemStatement:'Provide token bucket and sliding-window implementations behind one rate-limiter strategy interface.',classDiagram:[{className:'RateLimiterStrategy',type:'interface',fields:[],methods:['allow(key)']},{className:'TokenBucketLimiter',type:'class',fields:['capacity','refillRate','buckets'],methods:['allow(key)']},{className:'SlidingWindowLimiter',type:'class',fields:['limit','window','requests'],methods:['allow(key)']}],files:[{path:'rate_limiter.cpp',pattern:'Strategy',code:`#include <bits/stdc++.h>\nusing namespace std;using Clock=chrono::steady_clock;class RateLimiterStrategy{public:virtual bool allow(const string&)=0;virtual~RateLimiterStrategy()=default;};class TokenBucketLimiter:public RateLimiterStrategy{struct B{double tokens;Clock::time_point last;};double cap,rate;unordered_map<string,B>m;public:TokenBucketLimiter(double c,double r):cap(c),rate(r){}bool allow(const string&k)override{auto now=Clock::now();auto[it,ins]=m.try_emplace(k,B{cap,now});auto&b=it->second;b.tokens=min(cap,b.tokens+chrono::duration<double>(now-b.last).count()*rate);b.last=now;if(b.tokens<1)return false;b.tokens-=1;return true;}};class SlidingWindowLimiter:public RateLimiterStrategy{size_t limit;chrono::seconds window;unordered_map<string,deque<Clock::time_point>>m;public:SlidingWindowLimiter(size_t l,int sec):limit(l),window(sec){}bool allow(const string&k)override{auto now=Clock::now();auto&q=m[k];while(!q.empty()&&now-q.front()>=window)q.pop_front();if(q.size()>=limit)return false;q.push_back(now);return true;}};\n`}]},
{name:'Notification System',difficulty:'beginner',language:'cpp',problemStatement:'Design a notification subject that fans events out to interchangeable observers.',classDiagram:[{className:'Observer',type:'interface',fields:[],methods:['update(message)']},{className:'EmailObserver',type:'class',fields:['email'],methods:['update(message)']},{className:'SMSObserver',type:'class',fields:['phone'],methods:['update(message)']},{className:'NotificationService',type:'class',fields:['observers'],methods:['subscribe()','unsubscribe()','notify()']}],files:[{path:'notification.cpp',pattern:'Observer',code:`#include <bits/stdc++.h>\nusing namespace std;class Observer{public:virtual void update(const string&)=0;virtual~Observer()=default;};class EmailObserver:public Observer{string email;public:EmailObserver(string e):email(move(e)){}void update(const string&m)override{cout<<"EMAIL "<<email<<": "<<m<<"\\n";}};class SMSObserver:public Observer{string phone;public:SMSObserver(string p):phone(move(p)){}void update(const string&m)override{cout<<"SMS "<<phone<<": "<<m<<"\\n";}};class NotificationService{vector<shared_ptr<Observer>>obs;public:void subscribe(shared_ptr<Observer>o){obs.push_back(move(o));}void unsubscribe(const shared_ptr<Observer>&o){erase(obs,o);}void notify(const string&m){for(auto&o:obs)o->update(m);}};\n`}]}
];

const snippets=[
{category:'express',difficulty:'short',language:'javascript',patternTags:['middleware','error-handling'],code:commonErr},
{category:'mongodb',difficulty:'short',language:'javascript',patternTags:['mongoose','query'],code:\`const user = await User.findOneAndUpdate({ _id: userId }, { \\$set: { name } }, { new: true, runValidators: true });\`},
{category:'fastapi',difficulty:'short',language:'python',patternTags:['validation'],code:\`from pydantic import BaseModel, HttpUrl\\nclass CreateUrlRequest(BaseModel):\\n    original_url: HttpUrl\`},
{category:'microservices',difficulty:'medium',language:'javascript',patternTags:['circuit-breaker'],code:\`if (failureCount >= threshold) { circuitOpenUntil = Date.now() + resetMs; throw new Error('Circuit open'); }\`},
{category:'express',difficulty:'short',language:'javascript',patternTags:['validation','controller'],code:\`export async function createUser(req, res, next) {\\n  try {\\n    const user = await userService.create(req.body);\\n    return res.status(201).json({ success: true, data: user, error: null });\\n  } catch (error) {\\n    next(error);\\n  }\\n}\`},
{category:'express',difficulty:'medium',language:'javascript',patternTags:['auth','jwt'],code:\`export function requireAuth(req, res, next) {\\n  const token = req.headers.authorization?.replace('Bearer ', '');\\n  if (!token) return res.status(401).json({ success: false, data: null, error: 'Unauthorized' });\\n  req.user = jwt.verify(token, process.env.JWT_SECRET);\\n  next();\\n}\`},
{category:'mongodb',difficulty:'medium',language:'javascript',patternTags:['aggregation'],code:\`const totals = await Order.aggregate([\\n  { \\$match: { userId } },\\n  { \\$group: { _id: '$status', total: { \\$sum: '$amount' } } }\\n]);\`},
{category:'mongodb',difficulty:'long',language:'javascript',patternTags:['pagination','query'],code:\`const page = Math.max(Number(req.query.page) || 1, 1);\\nconst limit = Math.min(Number(req.query.limit) || 20, 100);\\nconst items = await Product.find(filter)\\n  .sort({ createdAt: -1 })\\n  .skip((page - 1) * limit)\\n  .limit(limit);\`},
{category:'fastapi',difficulty:'medium',language:'python',patternTags:['dependency','auth'],code:\`async def get_current_user(token: str = Depends(oauth2_scheme)):\\n    payload = jwt.decode(token, settings.jwt_secret, algorithms=[settings.jwt_algorithm])\\n    user = await user_repository.get_by_id(payload["sub"])\\n    if not user:\\n        raise HTTPException(status_code=401, detail="Unauthorized")\\n    return user\`},
{category:'fastapi',difficulty:'long',language:'python',patternTags:['router','service'],code:\`@router.post("/orders", status_code=status.HTTP_201_CREATED)\\nasync def create_order(payload: CreateOrderRequest, user=Depends(get_current_user)):\\n    order = await order_service.create(user.id, payload)\\n    return {"success": True, "data": order, "error": None}\`},
{category:'microservices',difficulty:'medium',language:'javascript',patternTags:['idempotency','redis'],code:\`const cached = await redis.get(\`idempotency:\\${key}\`);\\nif (cached) return JSON.parse(cached);\\nconst result = await handler();\\nawait redis.set(\`idempotency:\\${key}\`, JSON.stringify(result), 'EX', 3600);\\nreturn result;\`},
{category:'microservices',difficulty:'long',language:'javascript',patternTags:['queue','consumer'],code:\`consumer.on('message', async (message) => {\\n  try {\\n    await orderService.process(JSON.parse(message.value));\\n    await consumer.commitOffsets();\\n  } catch (error) {\\n    await dlq.publish(message, error);\\n  }\\n});\`}
];

export async function seed(){
  if(await Project.countDocuments()===0) await Project.insertMany(projects);
  if(await LLDProblem.countDocuments()===0) await LLDProblem.insertMany(lld);
  if(await Snippet.countDocuments()===0) await Snippet.insertMany(snippets);
}
