import { useEffect,useMemo,useRef,useState } from 'react';
import { Link,Route,Routes,useLocation,useNavigate,useParams } from 'react-router-dom';
import { Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis,Bar,BarChart } from 'recharts';
import { api } from './api';import { CodeEditor,DiffCodeEditor,Meter,Shell,Stat,Tree } from './components';import { liveMetrics } from './metrics';
type Any=Record<string,any>;
const elapsed=(start:number)=>Math.max(1,Math.floor((Date.now()-start)/1000));

function Dashboard(){
 const[d,setD]=useState<Any>({recent:[]});useEffect(()=>{api.get('/dashboard').then(r=>setD(r.data))},[]);
 const trend=(d.recent||[]).map((s:Any,i:number)=>({attempt:i+1,wpm:s.overall?.avgWpm||0,accuracy:s.overall?.avgAccuracy||0}));
 return <div><h1 className="text-4xl font-black">Train backend recall under pressure.</h1><p className="mt-2 text-zinc-400">Typing speed, architecture memory and LLD implementation in one practice loop.</p><div className="mt-6 grid gap-4 md:grid-cols-3"><Stat label="Attempts" value={d.attempts||0}/><Stat label="Average WPM" value={d.avgWpm||0}/><Stat label="Average accuracy" value={(d.avgAccuracy||0)+'%'}/></div>
 <div className="mt-6 card"><h2 className="font-bold">Recent progress</h2><div className="mt-4 h-64">{trend.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><XAxis dataKey="attempt"/><YAxis/><Tooltip/><Line type="monotone" dataKey="accuracy"/><Line type="monotone" dataKey="wpm"/></LineChart></ResponsiveContainer>:<div className="text-zinc-500">Complete a session to start your trend.</div>}</div></div>
 <div className="mt-6 grid gap-4 md:grid-cols-3"><Link className="card hover:border-zinc-500" to="/drills"><b>Snippet Drills</b><p className="text-zinc-400">Short boilerplate repetitions.</p></Link><Link className="card hover:border-zinc-500" to="/machine-coding"><b>Machine Coding</b><p className="text-zinc-400">Reconstruct complete backend projects.</p></Link><Link className="card hover:border-zinc-500" to="/lld"><b>LLD Practice</b><p className="text-zinc-400">Type classic C++ designs and patterns.</p></Link></div></div>
}

function Drills(){
 const[category,setCategory]=useState('mixed'),[mode,setMode]=useState('practice'),[preview,setPreview]=useState(10);const nav=useNavigate();
 return <div className="max-w-xl card"><h1 className="text-2xl font-bold">Snippet Drills</h1><label className="mt-5 block text-sm">Category</label><select className="input mt-2" value={category} onChange={e=>setCategory(e.target.value)}><option value="mixed">Mixed</option><option value="express">Express</option><option value="mongodb">MongoDB</option><option value="fastapi">FastAPI</option><option value="microservices">Microservices</option></select><label className="mt-4 block text-sm">Mode</label><select className="input mt-2" value={mode} onChange={e=>setMode(e.target.value)}><option value="practice">Practice</option><option value="evaluation">Evaluation · 5 snippets</option><option value="recall">Recall</option></select>{mode==='recall'&&<><label className="mt-4 block text-sm">Preview duration: {preview}s</label><input className="w-full" type="range" min="5" max="30" value={preview} onChange={e=>setPreview(+e.target.value)}/></>}<button className="btn mt-5" onClick={()=>nav('/drills/session',{state:{category,mode,preview}})}>Start session</button></div>
}

function DrillRun(){
 const location=useLocation(),cfg=(location.state as Any)||{category:'mixed',mode:'practice',preview:10},nav=useNavigate();
 const[state,setState]=useState<Any>({items:[],i:0,typed:'',start:Date.now(),results:[]}),[hidden,setHidden]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>{api.get('/snippets',{params:{category:cfg.category}}).then(r=>{let items=r.data;if(cfg.mode==='evaluation')items=[...items].sort(()=>Math.random()-.5).slice(0,5);setState((s:Any)=>({...s,items,start:Date.now()}))})},[]);
 useEffect(()=>{const t=setInterval(()=>setTick(x=>x+1),500);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(cfg.mode!=='recall')return;setHidden(false);const t=setTimeout(()=>setHidden(true),cfg.preview*1000);return()=>clearTimeout(t)},[state.i]);
 const cur=state.items[state.i];if(!cur)return <div>Loading session…</div>;const metrics=liveMetrics(state.typed,cur.code,elapsed(state.start));
 async function next(skipped=false){const sec=elapsed(state.start);const m=(await api.post('/metrics/item',{typed:state.typed,reference:cur.code,timeTakenSeconds:sec})).data;const result={itemId:cur._id,...m,timeTakenSeconds:sec,skipped,structureCorrect:true,group:cur.category};const results=[...state.results,result];if(state.i+1>=state.items.length){const session=(await api.post('/sessions',{type:'drill',mode:cfg.mode,itemsAttempted:results,timeTakenSeconds:results.reduce((s:number,x:Any)=>s+x.timeTakenSeconds,0),finishedBeforeTimeout:true})).data;nav('/results',{state:{session,title:'Snippet Drill Results'}});return;}setState({...state,i:state.i+1,typed:'',start:Date.now(),results});}
 useEffect(()=>{if(state.typed&&state.typed===cur.code){const t=setTimeout(()=>next(false),400);return()=>clearTimeout(t)}},[state.typed,cur.code]);
 return <div><div className="mb-4 grid gap-3 md:grid-cols-4"><Stat label="Snippet" value={state.i+1+'/'+state.items.length}/><Stat label="Elapsed" value={elapsed(state.start)+'s'}/><Stat label="Live WPM" value={metrics.wpm}/><Stat label="Accuracy" value={metrics.accuracy+'%'}/></div>{hidden?<div className="mb-4 card text-center text-zinc-400">Reference hidden — type from memory.</div>:<DiffCodeEditor reference={cur.code} value={state.typed} onChange={v=>setState({...state,typed:v})} language={cur.language}/>} {hidden&&<CodeEditor value={state.typed} onChange={v=>setState({...state,typed:v})} language={cur.language}/>}<div className="mt-3 flex gap-3"><button className="btn" onClick={()=>next(false)}>Submit item</button><button className="btn2" onClick={()=>next(true)}>Skip</button></div></div>
}

function Library({kind}:{kind:'projects'|'lld'}){
 const[data,setData]=useState<Any[]>([]),[difficulty,setDifficulty]=useState(''),[category,setCategory]=useState('');useEffect(()=>{api.get(kind==='projects'?'/projects':'/lld',{params:kind==='projects'?{difficulty:difficulty||undefined,category:category||undefined}:{}}).then(r=>setData(r.data))},[kind,difficulty,category]);const base=kind==='projects'?'/machine-coding':'/lld';
 return <div><h1 className="text-3xl font-black">{kind==='projects'?'Machine Coding Rounds':'LLD Practice'}</h1>{kind==='projects'&&<div className="mt-4 flex gap-3"><select className="input max-w-48" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">All difficulties</option><option>beginner</option><option>intermediate</option><option>advanced</option></select><select className="input max-w-48" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option><option value="express">Express</option><option value="fastapi">FastAPI</option></select></div>}<div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.map(x=><Link key={x._id} to={base+'/'+x._id} className="card hover:border-zinc-500"><div className="flex gap-2"><span className="badge">{x.difficulty}</span><span className="badge">{x.category||x.language}</span></div><h2 className="mt-4 text-xl font-bold">{x.name}</h2><p className="mt-2 text-sm text-zinc-400">{x.description||x.problemStatement}</p>{x.estimatedMinutes&&<p className="mt-4 text-sm">{x.estimatedMinutes} min</p>}</Link>)}</div></div>
}

function Detail({kind}:{kind:'project'|'lld'}){
 const{id}=useParams(),[x,setX]=useState<Any>(),[minutes,setMinutes]=useState(60);const nav=useNavigate();useEffect(()=>{api.get(kind==='project'?'/projects/'+id:'/lld/'+id).then(r=>{setX(r.data);setMinutes(r.data.estimatedMinutes||60)})},[id]);if(!x)return <div>Loading…</div>;
 return <div><h1 className="text-3xl font-black">{x.name}</h1><p className="mt-3 max-w-3xl text-zinc-400">{x.description||x.problemStatement}</p>{kind==='project'?<div className="mt-6 card"><h2 className="font-bold">Study the target folder structure before starting</h2><Tree paths={x.folderTree}/></div>:<div className="mt-6 grid gap-3 md:grid-cols-2">{x.classDiagram.map((c:Any)=><div className="card" key={c.className}><b>{c.type} {c.className}</b><p className="mt-2 text-sm text-zinc-400">{c.fields.join(', ')}</p><p className="text-sm">{c.methods.join(', ')}</p></div>)}</div>}<div className="mt-6 flex items-center gap-3"><select className="input max-w-32" value={minutes} onChange={e=>setMinutes(+e.target.value)}>{[30,45,60,90,120].map(m=><option value={m} key={m}>{m} min</option>)}</select><button className="btn" onClick={()=>nav((kind==='project'?'/machine-coding/':'/lld/')+id+'/run',{state:{minutes}})}>Start</button></div></div>
}

function Run({kind}:{kind:'project'|'lld'}){
 const{id}=useParams(),nav=useNavigate(),location=useLocation(),minutes=((location.state as Any)?.minutes||60),storageKey='backendtyper:'+kind+':'+id;
 const saved=useMemo(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'null')}catch{return null}},[storageKey]);
 const[x,setX]=useState<Any>(),[paths,setPaths]=useState<string[]>(saved?.paths||[]),[folders,setFolders]=useState<string[]>(saved?.folders||[]),[active,setActive]=useState(saved?.active||''),[typed,setTyped]=useState<Record<string,string>>(saved?.typed||{}),[hide,setHide]=useState(false),[start]=useState(saved?.start||Date.now()),[left,setLeft]=useState(minutes*60),submitting=useRef(false);
 useEffect(()=>{api.get(kind==='project'?'/projects/'+id:'/lld/'+id).then(r=>setX(r.data))},[id]);
 useEffect(()=>{const t=setInterval(()=>setLeft(Math.max(0,minutes*60-elapsed(start))),1000);return()=>clearInterval(t)},[minutes,start]);
 useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify({paths,folders,active,typed,start}))},[paths,folders,active,typed,start,storageKey]);
 useEffect(()=>{if(left===0&&x&&!submitting.current)submit(false)},[left,x]);
 if(!x)return <div>Loading…</div>;const ref=x.files.find((f:Any)=>f.path===active),live=ref?liveMetrics(typed[active]||'',ref.code,elapsed(start)):null;
 async function submit(early=true){if(submitting.current)return;submitting.current=true;const candidates=kind==='project'?paths:x.files.map((f:Any)=>f.path);const items=[];for(const p of candidates){const r=x.files.find((f:Any)=>f.path===p);if(!r)continue;const m=(await api.post('/metrics/item',{typed:typed[p]||'',reference:r.code,timeTakenSeconds:elapsed(start)})).data;items.push({itemId:p,...m,timeTakenSeconds:elapsed(start),skipped:!(typed[p]||'').length,structureCorrect:true,group:r.layer||r.pattern});}for(const r of x.files){if(!items.some((i:Any)=>i.itemId===r.path))items.push({itemId:r.path,wpm:0,accuracy:0,errorCount:r.code.length,timeTakenSeconds:0,skipped:true,structureCorrect:false,group:r.layer||r.pattern});}const session=(await api.post('/sessions',{type:kind==='project'?'machine-coding':'lld',mode:'evaluation',refId:id,itemsAttempted:items,timeLimitSeconds:minutes*60,timeTakenSeconds:Math.min(elapsed(start),minutes*60),finishedBeforeTimeout:early&&left>0})).data;localStorage.removeItem(storageKey);nav('/results',{state:{session,title:x.name}})}
 function addPath(){const p=prompt('Enter exact file path, e.g. src/controllers/url.controller.js')?.trim();if(p&&!paths.includes(p)){setPaths([...paths,p]);setActive(p)}}function addFolder(){const p=prompt('Enter folder path, e.g. src/controllers/')?.trim();if(p&&!folders.includes(p))setFolders([...folders,p.endsWith('/')?p:p+'/'])}
 const displayPaths=kind==='project'?paths:x.files.map((f:Any)=>f.path),remaining=left/(minutes*60),timerClass=remaining<=.1?'text-red-400':remaining<=.25?'text-amber-400':'';
 return <div><div className="mb-4 grid gap-3 md:grid-cols-4"><Stat label="Time left" value={<span className={timerClass}>{Math.floor(left/60)}:{String(left%60).padStart(2,'0')}</span>}/><Stat label="Files touched" value={displayPaths.filter(p=>(typed[p]||'').length>0).length+'/'+x.files.length}/><Stat label="Current WPM" value={live?.wpm||0}/><Stat label="Current accuracy" value={(live?.accuracy||0)+'%'}/></div><div className="mb-4 flex justify-end"><button className="btn" onClick={()=>submit(true)}>Submit round</button></div><div className="grid gap-4 lg:grid-cols-[280px_1fr]"><aside className="card h-fit"><div className="flex flex-wrap gap-2">{kind==='project'&&<><button className="btn2 text-xs" onClick={addPath}>+ New file</button><button className="btn2 text-xs" onClick={addFolder}>+ New folder</button></>}</div>{folders.length>0&&<div className="mt-4">{folders.map(f=><div className="py-1 text-sm text-zinc-500" key={f}>▸ {f}</div>)}</div>}<div className="mt-3 space-y-1">{displayPaths.map(p=><button key={p} className={'block w-full truncate rounded p-2 text-left text-sm '+(active===p?'bg-zinc-800':'hover:bg-zinc-900')} onClick={()=>setActive(p)}>{p}</button>)}</div></aside><section>{!active?<div className="card">Create/select a file to begin.</div>:!ref?<div className="card"><b>Unrecognized path</b><p className="mt-2 text-zinc-400">Keep it if this is intentional. It will not count as a structurally correct reference file.</p><CodeEditor value={typed[active]||''} onChange={v=>setTyped({...typed,[active]:v})}/></div>:<><div className="mb-2 flex items-center justify-between"><span className="text-sm text-zinc-400">{ref.layer||ref.pattern}</span><button className="btn2" onClick={()=>setHide(!hide)}>{hide?'Show':'Hide'} reference</button></div>{hide?<CodeEditor value={typed[active]||''} onChange={v=>setTyped({...typed,[active]:v})} language={x.language||'javascript'}/>:<DiffCodeEditor reference={ref.code} value={typed[active]||''} onChange={v=>setTyped({...typed,[active]:v})} language={x.language||'javascript'}/>}</>}</section></div></div>
}

function Results(){
 const location=useLocation(),nav=useNavigate(),payload=location.state as Any,session=payload?.session;if(!session)return <div className="card">No result is loaded. <Link className="underline" to="/history">Open history</Link>.</div>;
 const items=session.itemsAttempted||[],groups=Object.values(items.reduce((a:Any,i:Any)=>{const g=i.group||'other';a[g]??={group:g,total:0,count:0};a[g].total+=i.accuracy;a[g].count++;return a},{})).map((x:any)=>({group:x.group,accuracy:+(x.total/x.count).toFixed(1)}));
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-zinc-500">Final report</p><h1 className="text-3xl font-black">{payload?.title||'Session Results'}</h1></div><div className="text-5xl font-black">{session.overall.score}</div></div><div className="mt-6 grid gap-4 md:grid-cols-4"><Stat label="Average WPM" value={session.overall.avgWpm}/><Stat label="Accuracy" value={session.overall.avgAccuracy+'%'}/><Stat label="Completion" value={session.overall.completionPercent+'%'}/><Stat label="Total errors" value={session.overall.totalErrors}/></div><div className="mt-6 card"><h2 className="font-bold">Weakest area: {session.overall.weakestArea}</h2>{session.overall.timeLimitSeconds&&<p className="mt-2 text-zinc-400">Time: {Math.ceil(session.overall.timeTakenSeconds/60)} min used of {Math.ceil(session.overall.timeLimitSeconds/60)} min.</p>}</div>{groups.length>0&&<div className="mt-6 card"><h2 className="font-bold">Accuracy by layer / pattern</h2><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={groups}><XAxis dataKey="group"/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="accuracy"/></BarChart></ResponsiveContainer></div></div>}<div className="mt-6 overflow-auto card"><table className="w-full text-left text-sm"><thead><tr className="text-zinc-500"><th className="p-2">Item/file</th><th>Structure</th><th>Accuracy</th><th>WPM</th><th>Completed</th></tr></thead><tbody>{items.map((i:Any)=><tr className="border-t border-zinc-800" key={i.itemId}><td className="p-2 font-mono">{i.itemId}</td><td>{session.type==='machine-coding'?(i.structureCorrect?'Yes':'No'):'—'}</td><td>{i.accuracy}%</td><td>{i.wpm}</td><td>{i.skipped?'No':'Yes'}</td></tr>)}</tbody></table></div><div className="mt-5 flex gap-3"><button className="btn" onClick={()=>nav(session.type==='machine-coding'?'/machine-coding':session.type==='lld'?'/lld':'/drills')}>Practice again</button><Link className="btn2" to="/history">History</Link></div></div>
}

function History(){const[data,setData]=useState<Any[]>([]);useEffect(()=>{api.get('/sessions').then(r=>setData(r.data))},[]);return <div><h1 className="text-3xl font-black">Session History</h1><div className="mt-5 space-y-3">{data.map(s=><div className="card grid gap-2 md:grid-cols-7" key={s._id}><b>{s.type}</b><span>{s.mode}</span><span>{s.overall.avgWpm} WPM</span><span>{s.overall.avgAccuracy}% accuracy</span><span>{s.overall.completionPercent}% done</span><span>Score {s.overall.score}</span><span className="text-zinc-400">Weak: {s.overall.weakestArea}</span></div>)}</div></div>}

function Admin(){
 const[pin,setPin]=useState(''),[ok,setOk]=useState(false),[type,setType]=useState('snippet'),[json,setJson]=useState('{}'),[msg,setMsg]=useState('');
 const templates:Any={snippet:{category:'express',difficulty:'short',language:'javascript',patternTags:['middleware'],code:'// reference code'},project:{name:'New Project',description:'',category:'express',difficulty:'beginner',estimatedMinutes:45,folderTree:['src/'],files:[]},lld:{name:'New LLD Problem',problemStatement:'',language:'cpp',difficulty:'beginner',classDiagram:[],files:[]}};
 async function verify(){try{await api.post('/admin/verify',{}, {headers:{'x-admin-pin':pin}});setOk(true);setMsg('')}catch{setMsg('Invalid PIN')}}async function save(){try{const endpoint=type==='snippet'?'/admin/snippets':type==='project'?'/admin/projects':'/admin/lld';await api.post(endpoint,JSON.parse(json),{headers:{'x-admin-pin':pin}});setMsg('Saved successfully')}catch(e:any){setMsg(e.response?.data?.error||e.message)}}
 useEffect(()=>{setJson(JSON.stringify(templates[type],null,2))},[type]);
 if(!ok)return <div className="card max-w-sm"><h1 className="text-xl font-bold">Admin PIN</h1><input className="input mt-4" type="password" value={pin} onChange={e=>setPin(e.target.value)} onKeyDown={e=>e.key==='Enter'&&verify()}/><button className="btn mt-3" onClick={verify}>Unlock</button><p className="mt-2 text-sm text-zinc-400">{msg}</p></div>;
 return <div className="card"><h1 className="text-2xl font-bold">Content Management</h1><p className="mt-2 text-zinc-400">Choose a content type, edit the generated schema template, then save it to MongoDB.</p><select className="input mt-4" value={type} onChange={e=>setType(e.target.value)}><option value="snippet">Snippet</option><option value="project">Project</option><option value="lld">LLD Problem</option></select><textarea className="input mt-4 min-h-96 font-mono" value={json} onChange={e=>setJson(e.target.value)}/><button className="btn mt-3" onClick={save}>Save content</button><p className="mt-2">{msg}</p></div>
}

export default function App(){return <Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/drills" element={<Drills/>}/><Route path="/drills/session" element={<DrillRun/>}/><Route path="/machine-coding" element={<Library kind="projects"/>}/><Route path="/machine-coding/:id" element={<Detail kind="project"/>}/><Route path="/machine-coding/:id/run" element={<Run kind="project"/>}/><Route path="/lld" element={<Library kind="lld"/>}/><Route path="/lld/:id" element={<Detail kind="lld"/>}/><Route path="/lld/:id/run" element={<Run kind="lld"/>}/><Route path="/results" element={<Results/>}/><Route path="/history" element={<History/>}/><Route path="/admin" element={<Admin/>}/></Routes></Shell>}
